sudo: required
services:
  - docker

before_install:
  - docker build -t marco1022/docker-react -f Dockerfile.dev .

script:
  - docker run marco1022/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker_marco"
  env: "DockerMarco-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-654842437587"
  bucket_path: "docker_marco"
  on:
    branch: master
  access_key_id: $AWS_Access_key
  secret_access_key: 
    secure: "$AWS_Secret_access_key"